config/routes.rb
Rails.application.routes.draw do
  resources :create_news
  get 'welcome/index'

  resources :articles
  
  root 'welcome#index'

  
  resources :articles do
    resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/create_new.rb
class CreateNew < ApplicationRecord
      has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 
  # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
 
  def index
    @articles = Article.all
  end
 
  def show
    @article = Article.find(params[:id])
  end
 
  def new
    @article = Article.new
  end
 
  def edit
    @article = Article.find(params[:id])
  end
 
  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
 
  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end
 
  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    # http_basic_authenticate_with name: "1place", password: "1place", only: :destroy
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/create_news_controller.rb
class CreateNewsController < ApplicationController
  before_action :set_create_news, only: [:show, :edit, :update, :destroy]

  # GET /create_news
  # GET /create_news.json
  def index
    @create_news = CreateNew.all
  end

  # GET /create_news/1
  # GET /create_news/1.json
  def show
  end

  # GET /create_news/new
  def new
    @create_news = CreateNew.new
  end

  # GET /create_news/1/edit
  def edit
  end

  # POST /create_news
  # POST /create_news.json
  def create
    @create_news = CreateNew.new(create_news_params)

    respond_to do |format|
      if @create_news.save
        format.html { redirect_to @create_news, notice: 'Create new was successfully created.' }
        format.json { render :show, status: :created, location: @create_news }
      else
        format.html { render :new }
        format.json { render json: @create_news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /create_news/1
  # PATCH/PUT /create_news/1.json
  def update
    respond_to do |format|
      if @create_news.update(create_news_params)
        format.html { redirect_to @create_news, notice: 'Create new was successfully updated.' }
        format.json { render :show, status: :ok, location: @create_news }
      else
        format.html { render :edit }
        format.json { render json: @create_news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /create_news/1
  # DELETE /create_news/1.json
  def destroy
    @create_news.destroy
    respond_to do |format|
      format.html { redirect_to create_news_url, notice: 'Create new was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_create_news
      @create_news = CreateNew.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def create_news_params
      params.require(:create_news).permit(:bill_to, :contract_num, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/create_news_helper.rb
module CreateNewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Rental Contract</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Contract List</h1>
<%= link_to 'New Contract', new_article_path %>
<table>
  <tr>
    <th>Bill To</th>
    <th>Contents</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
  
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Destroy', article_path(article),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Contract</h1>

<div class="row">
    <div class="col-md-6">
      <input type="text" class="form-control" placeholder="Bill To">
      <input type="text" class="form-control" placeholder="Ship To">
    </div>
    <div class="col-md-6">
      <input type="text" class="form-control" placeholder="Contract #">
      <input type="text" class="form-control" placeholder="Date Out">
      <input type="text" class="form-control" placeholder="Time Out">
      <input type="text" class="form-control" placeholder="Off Rent">
      <input type="text" class="form-control" placeholder="Ordered By">
      <input type="text" class="form-control" placeholder="RL">
      <input type="text" class="form-control" placeholder="PO#">
      <label for="inputState">Terms</label>
      <select id="inputState" class="form-control">
        <option selected>Net 30 days</option>
        <option>...</option>
      </select>
      <input type="text" class="form-control" placeholder="HST #">

    </div>
  </div>
  <div class="row">
    <div class="col">
      <input type="textarea" class="form-control" placeholder="Notes">
      <input type="text" class="form-control" placeholder="Site Contact">
      </div>
  </div>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>New Rental Contract</strong>
  <div>Bill to: 
  <%= @article.title %>
  </div>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>
  
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/create_news/_form.html.erb
<%= form_with(model: create_news, local: true) do |form| %>
  <% if create_news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(create_news.errors.count, "error") %> prohibited this create_news from being saved:</h2>

      <ul>
      <% create_news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :bill_to %>
    <%= form.text_field :bill_to, id: :create_news_bill_to %>
  </div>

  <div class="field">
    <%= form.label :contract_num %>
    <%= form.text_field :contract_num, id: :create_news_contract_num %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :create_news_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/create_news/edit.html.erb
<h1>Editing Create News</h1>

<%= render 'form', create_news: @create_news %>

<%= link_to 'Show', @create_news %> |
<%= link_to 'Back', create_news_path %>

app/views/create_news/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Create News</h1>

<table>
  <thead>
    <tr>
      <th>Bill to</th>
      <th>Contract num</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @create_news.each do |create_news| %>
      <tr>
        <td><%= create_news.bill_to %></td>
        <td><%= create_news.contract_num %></td>
        <td><%= create_news.description %></td>
        <td><%= link_to 'Show', create_news %></td>
        <td><%= link_to 'Edit', edit_create_news_path(create_news) %></td>
        <td><%= link_to 'Destroy', create_news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Create News', new_create_news_path %>

app/views/create_news/new.html.erb
<h1>New Create News</h1>

<%= render 'form', create_news: @create_news %>

<%= link_to 'Back', create_news_path %>

app/views/create_news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bill to:</strong>
  <%= @create_news.bill_to %>
</p>

<p>
  <strong>Contract num:</strong>
  <%= @create_news.contract_num %>
</p>

<p>
  <strong>Description:</strong>
  <%= @create_news.description %>
</p>

<%= link_to 'Edit', edit_create_news_path(@create_news) %> |
<%= link_to 'Back', create_news_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/lc_input.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Blog" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Blog</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2019</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/welcome/index.html.erb
<h1>Liftco Contract Repository</h1>
<%= link_to 'Demo', controller: 'articles' %>